import { NextRequest, NextResponse } from 'next/server';

import { generateReviewMessage, type ReviewOutcome } from '@/lib/review-encouragement';

// POST { doneCount, totalCount, doneTitles, notDoneTitles }
// Return { message } — a short, warm, reflective sentence tailored to how the
// day went, generated by a fast headless `claude -p` call (falling back to a
// canned bucketed message on any failure). Purely advisory UX; nothing is
// written. Never surfaces an error to the client so the review flow can't break.
export async function POST(request: NextRequest) {
  try {
    const body = await request.json().catch(() => ({}));
    const outcome: ReviewOutcome = {
      doneCount: Number(body?.doneCount) || 0,
      totalCount: Number(body?.totalCount) || 0,
      doneTitles: Array.isArray(body?.doneTitles) ? body.doneTitles.map(String) : [],
      notDoneTitles: Array.isArray(body?.notDoneTitles) ? body.notDoneTitles.map(String) : [],
    };
    const message = await generateReviewMessage(outcome);
    return NextResponse.json({ message });
  } catch (error) {
    console.error('Error generating review message:', error);
    // Even on an unexpected failure, hand back a gentle default rather than an error.
    return NextResponse.json({ message: 'The day is done — rest, and start fresh tomorrow.' });
  }
}
